name: CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            node-version: 12.17.x
            prebuild: true
          - os: macos-latest
            node-version: 12.17.x
            prebuild: true
          - os: ubuntu-latest
            node-version: 12.17.x
            prebuild: true

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Set up Clang
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v1
        with:
          version: 10
          platform: x64
      
      - name: Install CMake, Ninja
        uses: lukka/get-cmake@latest
      
      - name: Build and Test
        run: |
          npm install
          npm test
        env:
          npm_config_build_from_source: true

      # Create a release on git refs that begin with 'v'
      - name: Release Prebuilt Binaries
        if: matrix.prebuild && startsWith(github.ref, 'refs/tags/v')
        run: npm run prebuild -- -u "$GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
